Vagrant.configure("2") do |config|
  config.vm.box = "chef/ubuntu-14.04"
  config.vm.network :private_network, ip: "10.0.2.100"
  #config.vm.network "forwarded_port", guest: 28017, host: 28017
  #config.ssh.forward_agent = true
  config.vm.provision :shell, :path => "./bootstrap.sh"
end
