application: zeta-rush-835
module: default
version: 7
runtime: go
api_version: go1
instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: 1s
  max_concurrent_requests: 500
handlers:
  - url: /favicon.ico
    static_files: resources/favicon.ico
    upload: resources/favicon.ico
  - url: /apple-touch-icon-precomposed.png
    static_files: resources/apple-touch-icon-precomposed.png
    upload: resources/apple-touch-icon-precomposed.png
  - url: /robots.txt
    static_files: resources/robots.txt
    upload: resources/robots.txt
  - url: /humans.txt
    static_files: resources/humans.txt
    upload: resources/humans.txt
  - url: /crossdomain.xml
    static_files: resources/crossdomain.xml
    upload: resources/crossdomain.xml
  - url: /css/*
    static_dir: resources/css
  - url: /js/*
    static_dir: resources/js
  - url: /fonts/*
    static_dir: resources/fonts
  - url: /.*
    script: _go_app
