application: focused-veld-834
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: static/html/index.html
  upload: static/html/index.html

- url: /(.*\.(html))$
  static_files: static/html/\1
  upload: static/html/.*\.(html)$

- url: /css/(.*)
  static_files: static/css/\1
  upload: static/css/.*

- url: /fonts/(.*)
  static_files: static/fonts/\1
  upload: static/fonts/.*

- url: /images/(.*)
  static_files: static/images/\1
  upload: static/images/.*

- url: /js/(.*)
  static_files: static/js/\1
  upload: static/js/.*

- url: /.*
  script: _go_app
