// Code generated by protoc-gen-go.
// source: protobee/connections.proto
// DO NOT EDIT!

/*
Package protobee is a generated protocol buffer package.

It is generated from these files:
	protobee/connections.proto

It has these top-level messages:
	Connections
	Connection
*/
package protobee

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Connections struct {
	Connection       []*Connection `protobuf:"bytes,1,rep,name=connection" json:"connection,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Connections) Reset()         { *m = Connections{} }
func (m *Connections) String() string { return proto.CompactTextString(m) }
func (*Connections) ProtoMessage()    {}

func (m *Connections) GetConnection() []*Connection {
	if m != nil {
		return m.Connection
	}
	return nil
}

type Connection struct {
	Transport        *string `protobuf:"bytes,1,req,name=transport" json:"transport,omitempty"`
	LocalAddress     *string `protobuf:"bytes,2,req,name=local_address" json:"local_address,omitempty"`
	LocalPort        *uint32 `protobuf:"varint,3,req,name=local_port" json:"local_port,omitempty"`
	RemoteAddress    *string `protobuf:"bytes,4,req,name=remote_address" json:"remote_address,omitempty"`
	RemotePort       *uint32 `protobuf:"varint,5,req,name=remote_port" json:"remote_port,omitempty"`
	Pid              *uint32 `protobuf:"varint,6,req,name=pid" json:"pid,omitempty"`
	Name             *string `protobuf:"bytes,7,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Connection) Reset()         { *m = Connection{} }
func (m *Connection) String() string { return proto.CompactTextString(m) }
func (*Connection) ProtoMessage()    {}

func (m *Connection) GetTransport() string {
	if m != nil && m.Transport != nil {
		return *m.Transport
	}
	return ""
}

func (m *Connection) GetLocalAddress() string {
	if m != nil && m.LocalAddress != nil {
		return *m.LocalAddress
	}
	return ""
}

func (m *Connection) GetLocalPort() uint32 {
	if m != nil && m.LocalPort != nil {
		return *m.LocalPort
	}
	return 0
}

func (m *Connection) GetRemoteAddress() string {
	if m != nil && m.RemoteAddress != nil {
		return *m.RemoteAddress
	}
	return ""
}

func (m *Connection) GetRemotePort() uint32 {
	if m != nil && m.RemotePort != nil {
		return *m.RemotePort
	}
	return 0
}

func (m *Connection) GetPid() uint32 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return 0
}

func (m *Connection) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func init() {
}
