- handlers:
  - {name: restart nginx, service: name=nginx state=restarted}
  - {name: restart supervisor, service: name=supervisor state=restarted}
  hosts: all
  sudo: true
  tasks:
  - {apt: update_cache=yes cache_valid_time=3600}
  - apt: pkg={{item}} state=latest
    name: ensure packages installed
    with_items: [python-apt, python-pycurl]
  - apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=7F0CEB10 state=present
  - apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' state=present
  - apt: pkg={{item}} state=latest
    with_items: [nginx, supervisor, mongodb-org, libmagic-dev]
  - {user: 'name=abbita generate_ssh_key=yes ssh_key_bits=2048'}
  - {file: 'name=/home/abbita/app state=directory'}
  - {unarchive: src=../builds/latest.tar.gz dest=/home/abbita/app, notify: restart supervisor}
  - {file: 'name=/home/abbita/app/abbita mode="u+x"'}
  - {file: path=/etc/nginx/sites-enabled/default state=absent}
  - {template: 'src=templates/supervisor.conf.j2 dest=/etc/supervisor/conf.d/abbita.conf', notify: restart supervisor}
  - {template: 'src=templates/nginx.conf.j2 dest=/etc/nginx/sites-enabled/abbita.conf' , notify: restart nginx}
