// generated by stringer -type=CommandType; DO NOT EDIT

package cassandredis

import "fmt"

const _CommandType_name = "CommandLPUSHCommandLRANGECommandUnknown"

var _CommandType_index = [...]uint8{12, 25, 39}

func (i CommandType) String() string {
	i -= 1
	if i >= CommandType(len(_CommandType_index)) {
		return fmt.Sprintf("CommandType(%d)", i+1)
	}
	hi := _CommandType_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _CommandType_index[i-1]
	}
	return _CommandType_name[lo:hi]
}
