application: gorgonzola-gophergala
version: 1
runtime: go
api_version: go1

handlers:
- url: /robots\.txt
  static_files: assets/robots.txt
  upload: assets/robots\.txt
- url: /favicon\.ico
  static_files: assets/favicon.ico
  upload: assets/favicon\.ico
- url: /task/update
  script: _go_app
  login: admin
- url: /_ah/queue/go/delay
  script: _go_app
  login: admin
- url: /.*
  script: _go_app
