---
servergroups:
  localhost:
  web:
    - host: localhost
      username: "vagrant"
      password: "vagrant"
      port: 2222

tasks:
  sayhello:
    steps:
      - command: "echo"
        args:
        - "hello"
  mailhello:
    steps:
      - plugin: "mailgun"
        options:
          user: key-0000000000000000
          endpoint: sandbox00000.mailgun.org
          from: "testdummy@notavaliddomain.io"
          to: "testdummy2@notavaliddomain.io"
          subject: "Just a test to say hello!"
          text: "This is the body of the text"
  deploy:
    steps:
      - command: "echo"
        args:
        - "deploying..."
      - plugin: "env"
      - command: "echo"
        args:
        - "- mid deploy -"
      - command: "echo"
        args:
        - "deployed!"
      - plugin: "ping"
        options:
          count: 3
          url: www.golang.org
  raiseerror:
    steps:
      - command: "echo"
        args:
        - "raise error"
      - command: "test"
        args:
        - "this should break"
triggers:
  testwebhook:
    type: webhook
    endpoint: prod
    servergroup: localhost
    task: sayhello
  gitpush:
    type: github-webhook
    endpoint: gitpush
    secret: mygithubsecrethere
    servergroup: localhost
    task: sayhello
  monitor:
    type: periodic
    period: 600
    servergroup: localhost
    task: sayhello
interfaces:
  web:
    settings:
      folder: /gokiss
      port: 20000
      sessionsecret: eIvObvXEiCzUZ61doiOX
    users:
      - username: gokiss
        password: default